server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bdprestabancoms
    username: root
    password: Chile&2023
jpa:
  hibernate:
    ddl-auto: update
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/
